unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g history-limit 100000

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -s escape-time 0

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status-interval 1

bind r source-file ~/.tmux.conf \; display-message "Tmux configuration reloaded."

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status-style "bg=#000000,fg=#cba6f7"

set -g window-status-format "#[fg=#6c7086,bg=#000000] #I #{?window_zoomed_flag,🔍,}#W "

set -g window-status-current-format "#[fg=#000000,bg=#cba6f7,bold] #I #{?window_zoomed_flag,🔍,}#W "

set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#cba6f7"

set -g message-style "bg=#cba6f7,fg=#000000,bold"

set -g status-left "#[fg=#000000,bg=#cba6f7,bold]  #S #[bg=#000000] "
set -g status-left-length 40

set -g status-right "#[fg=#cba6f7,bg=#000000] %H:%M #[fg=#000000,bg=#cba6f7,bold] OS DEV "
set -g status-right-length 50
set -g status-justify left
