term xterm-256color

background #000000
foreground #d4cfd8
selection_background #2a2a3e
selection_foreground #ffffff

cursor #7e68b5
cursor_shape block
cursor_blink_interval 0.5

color0  #1a1a1a
color1  #e06c75
color2  #98c379
color3  #e5c07b
color4  #7e68b5
color5  #c678dd
color6  #56b6c2
color7  #d4cfd8

color8  #4b4b4b
color9  #ff7b86
color10 #b5e8a0
color11 #f2d294
color12 #9d8ad6
color13 #d79af1
color14 #61c4d0
color15 #ffffff

background_opacity 0.95
dynamic_background_opacity yes
#font_family MartianMono Nerd Font Propo
font_size 10.0
disable_ligatures never

window_padding_width 10
window_margin_width 0
